DROP DATABASE IF EXISTS Hangman_db;
CREATE DATABASE Hangman_db;

USE Hangman_db;

CREATE TABLE Users (
	userID INT(11) PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(50) NOT NULL,
	pw VARCHAR(50) NOT NULL
);

CREATE TABLE Stats (
	statsID INT(11) PRIMARY KEY AUTO_INCREMENT,
	userID INT(11) NOT NULL,
	wins INT(11) NOT NULL,
	losses INT(11) NOT NULL,
    FOREIGN KEY fk1(userID) REFERENCES Users(userID)
);

